services:

    _defaults:
        autowire: true
        autoconfigure: true

    # tool installer
    LuceneSearchBundle\Tool\Install: ~
        public: true
        
    # configuration
    LuceneSearchBundle\Configuration\Configuration: ~

    # tool crawler state
    LuceneSearchBundle\Tool\CrawlerState: ~
